# Data Frames 
### (Data Frames = combination of multiple series)

#### Creating a Data Frame

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [6]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name", "Age", "City", "salary"]
df2 = pd.DataFrame(data_list, columns= columns)
df2

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

#### Selecting and indexing of columns

In [5]:
df2

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [7]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

#### Creating a new column

In [8]:
df2["Designation"] = ["Doctor", "Engineer", "Teacher", "Doctor"]
df2

    Name  Age      City  salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000      Doctor

#### Removing Cloumns

In [9]:
df2.drop("Designation", axis = 1)   #only removes column in secondary storage

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df2

    Name  Age      City  salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000     Teacher
3  Linda   42    London   85000      Doctor

In [11]:
df2.drop("Designation", axis = 1, inplace= True)    #Inplace removes data from main data farame

In [12]:
df2

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2.drop(0,axis = 0)    #for removing perticular

    Name  Age    City  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

#### Selecting Rows

In [15]:
df2

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
df2.loc[[0,1]]

   Name  Age      City  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [19]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

#### Selecting Subset of Rows and Columns

In [20]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [21]:
df2

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [24]:
df2.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

#### Conditional Selection

In [25]:
df2

    Name  Age      City  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [33]:
# I only wants to see those people whose age is above 30 
df2[df2["Age"] > 30]

    Name  Age    City  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [35]:
# I only wants to see those people whose age is above 30 and their city must be Paris
df2[(df2["Age"] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  salary
1  Anna   34  Paris   70000